# Test stack — API + E2E browser tests via Playwright
# Usage: "make test"

services:
  quizapp:
    extends:
      file: compose.base.yml
      service: quizapp-base
    build:
      context: .
      dockerfile: app/Dockerfile
      target: prod
    # OCPA-R14: Restart policy
    restart: "no"

  test:
    build:
      context: ./tests/e2e
      dockerfile: Dockerfile
    # OCPA-R16: Cross-platform compatibility
    platform: linux/amd64
    depends_on:
      quizapp:
        condition: service_healthy
    # OCPA-R10: Logging limits
    logging:
      options:
        max-size: "1m"
